#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/honeyd

PIDFILE=/run/honeyd.pid
PID=$(cat $PIDFILE 2>/dev/null)
if ! readlink -q /proc/$PID/exe | grep -q '^/usr/sbin/honeyd'; then
	PID=
	rm $PIDFILE 2>/dev/null
fi

case "$1" in
	start)
		stat_busy 'Starting Honeyd'
		[[ -z $PID ]] && /usr/bin/honeyd -d -f $HONEYD_CONF $HONEYD_SUBNET $HONEYD_ARGS
		if [[ $? -gt 0 ]]; then
			stat_fail
		else
			add_daemon honeyd
			stat_done
		fi
		;;
	stop)
		stat_busy 'Stopping Honeyd'
		[[ ! -z $PID ]] && kill $PID &> /dev/null
		if [[ $? -gt 0 ]]; then
			stat_fail
		else
			rm_daemon honeyd
			stat_done
		fi
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
esac
exit 0
